version: "3.9"
services:
  bringg-mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./datavolume:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: andy
      MYSQL_PASSWORD: Andyli!!!0217
      MYSQL_DATABASE: stock_tracker
